name: Publish SentinelAI to PyPI

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Build and publish Python distro to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build dependencies
        run: pip install build
        

      - name: Build binary wheel and source tarball
        run: python -m build
        working-directory: ./cli

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1